[project]
name = "aggregator-library"
authors = ["Decentralized Data Team"]
description = "A flexible smart contract library for managing decentralized data streams"
telemetry = false
requirements = []

[contracts.data-aggregator]
path = "contracts/data-aggregator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
